correct_data = {
    "audible": {
        "name": {"type": "TEXT", "regex": False},
        "author": {"type": "TEXT", "regex": False},
        "narrator": {"type": "TEXT", "regex": False},
        "time": {"type": "TIME", "regex": True},
        "releasedate": {"type": "DATE", "regex": True},
        "language": {"type": "CATEGORY", "regex": False},
        "stars": {"type": "TEXT", "regex": False},
        "price": {"type": "FLOAT", "regex": False},
    },
    "car_price": {
        "year": {"type": "DATE", "regex": True},
        "make": {"type": "CATEGORY", "regex": False},
        "model": {"type": "CATEGORY", "regex": False},
        "trim": {"type": "CATEGORY", "regex": False},
        "body": {"type": "CATEGORY", "regex": False},
        "transmission": {"type": "CATEGORY", "regex": False},
        "vin": {"type": "TEXT", "regex": False},
        "state": {"type": "CATEGORY", "regex": False},
        "condition": {"type": "INT", "regex": False},
        "odometer": {"type": "INT", "regex": False},
        "color": {"type": "CATEGORY", "regex": False},
        "interior": {"type": "CATEGORY", "regex": False},
        "seller": {"type": "TEXT", "regex": False},
        "mmr": {"type": "INT", "regex": False},
        "sellingprice":{"type": "INT", "regex": False},
        "saledate": {"type": "DATETIME", "regex": True},
    },
    "glassdoor": {
        "index": {"type": "INT", "regex": False},
        "Job Title": {"type": "TEXT", "regex": False},
        "Salary Estimate": {"type": "TEXT", "regex": False},
        "Job Description": {"type": "TEXT", "regex": False},
        "Rating": {"type": "FLOAT", "regex": False},
        "Company Name": {"type": "TEXT", "regex": False},
        "Location": {"type": "CATEGORY", "regex": False},
        "Headquarters": {"type": "TEXT", "regex": False},
        "Size": {"type": "CATEGORY", "regex": False},
        "Founded": {"type": "TEXT", "regex": False},
        "Type of ownership": {"type": "CATEGORY", "regex": False},
        "Industry": {"type": "CATEGORY", "regex": False},
        "Sector": {"type": "CATEGORY", "regex": False},
        "Revenue": {"type": "TEXT", "regex": False},
        "Competitors": {"type": "TEXT", "regex": False},
    },
    "kickstarter": {
        "ID ": {"type": "INT", "regex": False},
        "name ": {"type": "TEXT", "regex": False},
        "category ": {"type": "CATEGORY", "regex": False} ,
        "main_category ": {"type": "CATEGORY", "regex": False},
        "currency ": {"type": "CATEGORY", "regex": False},
        "deadline ": {"type": "DATETIME", "regex": True},
        "goal ": {"type": "INT", "regex": False},
        "launched ": {"type": "DATETIME", "regex": True},
        "pledged ": {"type": "FLOAT", "regex": False},
        "state ": {"type": "CATEGORY", "regex": False},
        "backers ": {"type": "INT", "regex": False},
        "country ": {"type": "CATEGORY", "regex": False},
        "usd pledged ": {"type": "FLOAT", "regex": False},
    },
    "salaries": {
        "work_year": {"type": "INT", "regex": False},
        "experience_level": {"type": "CATEGORY", "regex": False},
        "employment_type":{"type": "CATEGORY", "regex": False} ,
        "job_title":{"type": "CATEGORY", "regex": False},
        "salary":{"type": "INT", "regex": False},
        "salary_currency":{"type": "CATEGORY", "regex": False},
        "salary_in_usd":{"type": "INT", "regex": False},
        "employee_residence":{"type": "CATEGORY", "regex": False},
        "remote_ratio":{"type": "INT", "regex": False},
        "company_location":{"type": "CATEGORY", "regex": False},
        "company_size":{"type": "CATEGORY", "regex": False},
    },
    "wearables": {
        "timestamp": {"type": "DATETIME", "regex": True},
        "back_x": {"type": "FLOAT", "regex": False},
        "back_y": {"type": "FLOAT", "regex": False},
        "back_z": {"type": "FLOAT", "regex": False},
        "thigh_x": {"type": "FLOAT", "regex": False},
        "thigh_y": {"type": "FLOAT", "regex": False},
        "thigh_z": {"type": "FLOAT", "regex": False},
        "label": {"type": "INT", "regex": False}

    }


}